name: sample workFlow
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sampleJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "sample action"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List files in repository
        run: |
          echo "the repository ${{ github.repository }} contains the following files:"
          tree
